name: Main
on: workflow_dispatch

# permissions: write-all

jobs:
  Build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: windows
            artifactName: Windows
            artifactPath: export/release/windows/bin/*
          - name: Windows x64
            os: windows-2022
            buildArgs: "windows -X64 -D HXCPP_X64 -D 64bits"
            artifactName: Windows x64
            artifactPath: export/release/windows/64bits/bin/*
          - name: Windows x32
            os: windows-2022
            buildArgs: "windows -X32 -D HXCPP_X32 -D 32bits"
            artifactName: Windows x32
            artifactPath: export/release/windows/32bits/bin/*
          - name: Linux
            os: ubuntu-22.04
            buildArgs: linux
            artifactName: Linux
            artifactPath: export/release/linux/bin/*
          - name: MacOS
            os: macos-15
            buildArgs: mac
            artifactName: MacOS
            artifactPath: export/release/macos/bin/*
          - name: Android
            os: macos-15
            buildArgs: "android -ONLY_ARMV7"
            artifactName: Android
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: iOS
            os: macos-15
            buildArgs: "ios -nosign"
            artifactName: IOS
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}
