name: Release
on: workflow_dispatch

permissions:
  contents: write
  discussions: write

env:
  PROJECT_NAME: ModsEngine

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Windows-PNG
            os: windows-latest
            buildArgs: "windows -final -D officialBuild"
            artifactName: windowsBuild-PNG
            artifactPath: export\release\windows\bin\*
          - name: Android-PNG
            os: ubuntu-22.04
            buildArgs: "android -final -D officialBuild"
            artifactName: androidBuild-PNG
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: Android-ASTC
            os: ubuntu-22.04
            buildArgs: "android -final -D officialBuild -D USING_GPU_TEXTURES"
            artifactName: androidBuild-ASTC
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: iOS-PNG
            os: macos-15
            buildArgs: "ios -final -nosign -D officialBuild"
            artifactName: iOSBuild-PNG
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
          - name: iOS-ASTC
            os: macos-15
            buildArgs: "ios -final -nosign -D officialBuild -D USING_GPU_TEXTURES"
            artifactName: iOSBuild-ASTC
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Windows Build
        uses: actions/download-artifact@main
        with:
          name: windowsBuild-PNG
          path: /home/runner/windowsBuild-PNG

      - name: Zip Windows Build For Release
        run: |
          cd /home/runner/windowsBuild-PNG
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Windows-PNG.zip" .
          
      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild-PNG
           path: /home/runner

      - name: Move Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/${{ env.PROJECT_NAME }}-png.apk

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
           name: iOSBuild-PNG
           path: ${{ github.workspace }}

      - name: Move iOS File
        run: mv ${{ github.workspace }}/${{ env.PROJECT_NAME }}.ipa /home/runner/${{ env.PROJECT_NAME }}-png.ipa

      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild-ASTC
           path: /home/runner

      - name: Move Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/${{ env.PROJECT_NAME }}-Android-astc.apk

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
           name: iOSBuild-ASTC
           path: ${{ github.workspace }}

      - name: Move iOS File
        run: mv ${{ github.workspace }}/${{ env.PROJECT_NAME }}.ipa /home/runner/${{ env.PROJECT_NAME }}-astc.ipa

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "release : 6.9.9"
          tag_name: "release-${{ needs.get-commit-hash.outputs.commit_hash }}"
          make_latest: true
          files: |
            /home/runner/*-png.apk
            /home/runner/*-png.ipa
            /home/runner/*-astc.apk
            /home/runner/*-astc.ipa
            /home/runner/*-PNG.zip
