name: Release Test
on: workflow_dispatch

permissions:
  contents: write
  discussions: write

env:
  PROJECT_NAME: ModsEngine

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Windows x86_64
            os: windows-2025
            buildArgs: "windows -final -D officialBuild"
            artifactName: windowsBuild-x86_64
            artifactPath: export\release\windows\bin\*
          - name: Linux x86_64
            os: ubuntu-22.04
            buildArgs: "linux -final -D officialBuild"
            artifactName: linuxBuild-x86_64
            artifactPath: export/release/linux/bin/*
          - name: Linux ARM64
            os: ubuntu-22.04-arm
            buildArgs: "linux -arm64 -final -D HXCPP_ARM64 -D officialBuild"
            artifactName: linuxBuild-arm64
            artifactPath: export/release/linux/bin/*
          - name: macOS x86_64
            os: macos-15
            buildArgs: "mac -final -64 -D HXCPP_M64 -D officialBuild"
            artifactName: macOSBuild-x86_64
            artifactPath: export/release/macos/bin/*
          - name: macOS ARM64
            os: macos-15
            buildArgs: "mac -final -arm64 -D HXCPP_ARM64 -D officialBuild"
            artifactName: macOSBuild-arm64
            artifactPath: export/release/macos/bin/*
          - name: Android
            os: macos-15
            buildArgs: "android -final -D officialBuild"
            artifactName: androidBuild
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: iOS
            os: macos-15
            buildArgs: "ios -eval -final -nosign -D officialBuild"
            artifactName: iOSBuild
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Windows Build
        uses: actions/download-artifact@main
        with:
          name: Windows
          path: /home/runner/Windows

      - name: Zip Windows Build For Release
        run: |
          cd /home/runner/Windows
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Windows.zip" .

      - name: Download Windows x64 Build
        uses: actions/download-artifact@main
        with:
          name: Windows x64
          path: /home/runner/Windows

      - name: Zip Windows x64 Build For Release
        run: |
          cd /home/runner/Windows x64
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Windows-x64.zip" .

      - name: Download Windows x32 Build
        uses: actions/download-artifact@main
        with:
          name: Windows x32
          path: /home/runner/Windows x32

      - name: Zip Windows x32 Build For Release
        run: |
          cd /home/runner/Windows x32
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Windows-x32.zip" .

      - name: Download Linux Build
        uses: actions/download-artifact@main
        with:
          name: Linux
          path: /home/runner/Linux

      - name: Tar Linux Build For Release
        run: |
          cd /home/runner/Linux
          tar czf "/home/runner/${{ env.PROJECT_NAME }}-Linux.tar" .

      - name: Download MacOS Build
        uses: actions/download-artifact@main
        with:
          name: MacOS
          path: /home/runner/MacOS

      - name: Tar MacOS Build For Release
        run: |
          cd /home/runner/MacOS
          tar czf "/home/runner/${{ env.PROJECT_NAME }}-MacOS.tar" .

      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
          name: Android
          path: /home/runner

      - name: Move Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/${{ env.PROJECT_NAME }}-Android.apk

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
          name: iOS
          path: ${{ github.workspace }}

      - name: Move iOS File
        run: mv ${{ github.workspace }}/${{ env.PROJECT_NAME }}.ipa /home/runner/${{ env.PROJECT_NAME }}-iOS.ipa

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "6.9.9"
          tag_name: "6.9.9"
          prerelease: false
          files: |
            /home/runner/*.apk
            /home/runner/*.ipa
            /home/runner/*.tar
            /home/runner/*.zip
